version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: smartcity_postgres
    environment:
      POSTGRES_USER: smartcity
      POSTGRES_PASSWORD: smartcity
      POSTGRES_DB: smartcity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
